version: '3'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MovieRentalDb
    ports:
        - "5433:5432"
    restart: always
    volumes:
        - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
