// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRental.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieRental.Infrastructure.Migrations
{
    [DbContext(typeof(MovieRentalDbContext))]
    [Migration("20231118145214_SeedCountriesOrigin")]
    partial class SeedCountriesOrigin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CountryOfOriginMovie", b =>
                {
                    b.Property<int>("CountriesOfOriginId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.HasKey("CountriesOfOriginId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CountryOfOriginMovie");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.CountryOfOrigin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAlpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.ToTable("CountriesOfOrigin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommonName = "Afghanistan",
                            NameAlpha3Code = "AFG"
                        },
                        new
                        {
                            Id = 2,
                            CommonName = "Åland Islands",
                            NameAlpha3Code = "ALA"
                        },
                        new
                        {
                            Id = 3,
                            CommonName = "Albania",
                            NameAlpha3Code = "ALB"
                        },
                        new
                        {
                            Id = 4,
                            CommonName = "Algeria",
                            NameAlpha3Code = "DZA"
                        },
                        new
                        {
                            Id = 5,
                            CommonName = "American Samoa",
                            NameAlpha3Code = "ASM"
                        },
                        new
                        {
                            Id = 6,
                            CommonName = "Andorra",
                            NameAlpha3Code = "AND"
                        },
                        new
                        {
                            Id = 7,
                            CommonName = "Angola",
                            NameAlpha3Code = "AGO"
                        },
                        new
                        {
                            Id = 8,
                            CommonName = "Anguilla",
                            NameAlpha3Code = "AIA"
                        },
                        new
                        {
                            Id = 9,
                            CommonName = "Antarctica",
                            NameAlpha3Code = "ATA"
                        },
                        new
                        {
                            Id = 10,
                            CommonName = "Antigua and Barbuda",
                            NameAlpha3Code = "ATG"
                        },
                        new
                        {
                            Id = 11,
                            CommonName = "Argentina",
                            NameAlpha3Code = "ARG"
                        },
                        new
                        {
                            Id = 12,
                            CommonName = "Armenia",
                            NameAlpha3Code = "ARM"
                        },
                        new
                        {
                            Id = 13,
                            CommonName = "Aruba",
                            NameAlpha3Code = "ABW"
                        },
                        new
                        {
                            Id = 14,
                            CommonName = "Australia",
                            NameAlpha3Code = "AUS"
                        },
                        new
                        {
                            Id = 15,
                            CommonName = "Austria",
                            NameAlpha3Code = "AUT"
                        },
                        new
                        {
                            Id = 16,
                            CommonName = "Azerbaijan",
                            NameAlpha3Code = "AZE"
                        },
                        new
                        {
                            Id = 17,
                            CommonName = "Bahamas",
                            NameAlpha3Code = "BHS"
                        },
                        new
                        {
                            Id = 18,
                            CommonName = "Bahrain",
                            NameAlpha3Code = "BHR"
                        },
                        new
                        {
                            Id = 19,
                            CommonName = "Bangladesh",
                            NameAlpha3Code = "BGD"
                        },
                        new
                        {
                            Id = 20,
                            CommonName = "Barbados",
                            NameAlpha3Code = "BRB"
                        },
                        new
                        {
                            Id = 21,
                            CommonName = "Belarus",
                            NameAlpha3Code = "BLR"
                        },
                        new
                        {
                            Id = 22,
                            CommonName = "Belgium",
                            NameAlpha3Code = "BEL"
                        },
                        new
                        {
                            Id = 23,
                            CommonName = "Belize",
                            NameAlpha3Code = "BLZ"
                        },
                        new
                        {
                            Id = 24,
                            CommonName = "Benin",
                            NameAlpha3Code = "BEN"
                        },
                        new
                        {
                            Id = 25,
                            CommonName = "Bermuda",
                            NameAlpha3Code = "BMU"
                        },
                        new
                        {
                            Id = 26,
                            CommonName = "Bhutan",
                            NameAlpha3Code = "BTN"
                        },
                        new
                        {
                            Id = 27,
                            CommonName = "Bolivia",
                            NameAlpha3Code = "BOL"
                        },
                        new
                        {
                            Id = 28,
                            CommonName = "Bosnia and Herzegovina",
                            NameAlpha3Code = "BIH"
                        },
                        new
                        {
                            Id = 29,
                            CommonName = "Botswana",
                            NameAlpha3Code = "BWA"
                        },
                        new
                        {
                            Id = 30,
                            CommonName = "Bouvet Island",
                            NameAlpha3Code = "BVT"
                        },
                        new
                        {
                            Id = 31,
                            CommonName = "Brazil",
                            NameAlpha3Code = "BRA"
                        },
                        new
                        {
                            Id = 32,
                            CommonName = "British Indian Ocean Territory",
                            NameAlpha3Code = "IOT"
                        },
                        new
                        {
                            Id = 33,
                            CommonName = "British Virgin Islands",
                            NameAlpha3Code = "VGB"
                        },
                        new
                        {
                            Id = 34,
                            CommonName = "Brunei",
                            NameAlpha3Code = "BRN"
                        },
                        new
                        {
                            Id = 35,
                            CommonName = "Bulgaria",
                            NameAlpha3Code = "BGR"
                        },
                        new
                        {
                            Id = 36,
                            CommonName = "Burkina Faso",
                            NameAlpha3Code = "BFA"
                        },
                        new
                        {
                            Id = 37,
                            CommonName = "Burundi",
                            NameAlpha3Code = "BDI"
                        },
                        new
                        {
                            Id = 38,
                            CommonName = "Cambodia",
                            NameAlpha3Code = "KHM"
                        },
                        new
                        {
                            Id = 39,
                            CommonName = "Cameroon",
                            NameAlpha3Code = "CMR"
                        },
                        new
                        {
                            Id = 40,
                            CommonName = "Canada",
                            NameAlpha3Code = "CAN"
                        },
                        new
                        {
                            Id = 41,
                            CommonName = "Cape Verde",
                            NameAlpha3Code = "CPV"
                        },
                        new
                        {
                            Id = 42,
                            CommonName = "Caribbean Netherlands",
                            NameAlpha3Code = "BES"
                        },
                        new
                        {
                            Id = 43,
                            CommonName = "Cayman Islands",
                            NameAlpha3Code = "CYM"
                        },
                        new
                        {
                            Id = 44,
                            CommonName = "Central African Republic",
                            NameAlpha3Code = "CAF"
                        },
                        new
                        {
                            Id = 45,
                            CommonName = "Chad",
                            NameAlpha3Code = "TCD"
                        },
                        new
                        {
                            Id = 46,
                            CommonName = "Chile",
                            NameAlpha3Code = "CHL"
                        },
                        new
                        {
                            Id = 47,
                            CommonName = "China",
                            NameAlpha3Code = "CHN"
                        },
                        new
                        {
                            Id = 48,
                            CommonName = "Christmas Island",
                            NameAlpha3Code = "CXR"
                        },
                        new
                        {
                            Id = 49,
                            CommonName = "Cocos (Keeling) Islands",
                            NameAlpha3Code = "CCK"
                        },
                        new
                        {
                            Id = 50,
                            CommonName = "Colombia",
                            NameAlpha3Code = "COL"
                        },
                        new
                        {
                            Id = 51,
                            CommonName = "Comoros",
                            NameAlpha3Code = "COM"
                        },
                        new
                        {
                            Id = 52,
                            CommonName = "DR Congo",
                            NameAlpha3Code = "COD"
                        },
                        new
                        {
                            Id = 53,
                            CommonName = "Cook Islands",
                            NameAlpha3Code = "COK"
                        },
                        new
                        {
                            Id = 54,
                            CommonName = "Costa Rica",
                            NameAlpha3Code = "CRI"
                        },
                        new
                        {
                            Id = 55,
                            CommonName = "Croatia",
                            NameAlpha3Code = "HRV"
                        },
                        new
                        {
                            Id = 56,
                            CommonName = "Cuba",
                            NameAlpha3Code = "CUB"
                        },
                        new
                        {
                            Id = 57,
                            CommonName = "Curaçao",
                            NameAlpha3Code = "CUW"
                        },
                        new
                        {
                            Id = 58,
                            CommonName = "Cyprus",
                            NameAlpha3Code = "CYP"
                        },
                        new
                        {
                            Id = 59,
                            CommonName = "Czechia",
                            NameAlpha3Code = "CZE"
                        },
                        new
                        {
                            Id = 60,
                            CommonName = "Denmark",
                            NameAlpha3Code = "DNK"
                        },
                        new
                        {
                            Id = 61,
                            CommonName = "Djibouti",
                            NameAlpha3Code = "DJI"
                        },
                        new
                        {
                            Id = 62,
                            CommonName = "Dominica",
                            NameAlpha3Code = "DMA"
                        },
                        new
                        {
                            Id = 63,
                            CommonName = "Dominican Republic",
                            NameAlpha3Code = "DOM"
                        },
                        new
                        {
                            Id = 64,
                            CommonName = "Ecuador",
                            NameAlpha3Code = "ECU"
                        },
                        new
                        {
                            Id = 65,
                            CommonName = "Egypt",
                            NameAlpha3Code = "EGY"
                        },
                        new
                        {
                            Id = 66,
                            CommonName = "El Salvador",
                            NameAlpha3Code = "SLV"
                        },
                        new
                        {
                            Id = 67,
                            CommonName = "Equatorial Guinea",
                            NameAlpha3Code = "GNQ"
                        },
                        new
                        {
                            Id = 68,
                            CommonName = "Eritrea",
                            NameAlpha3Code = "ERI"
                        },
                        new
                        {
                            Id = 69,
                            CommonName = "Estonia",
                            NameAlpha3Code = "EST"
                        },
                        new
                        {
                            Id = 70,
                            CommonName = "Ethiopia",
                            NameAlpha3Code = "ETH"
                        },
                        new
                        {
                            Id = 71,
                            CommonName = "Falkland Islands",
                            NameAlpha3Code = "FLK"
                        },
                        new
                        {
                            Id = 72,
                            CommonName = "Faroe Islands",
                            NameAlpha3Code = "FRO"
                        },
                        new
                        {
                            Id = 73,
                            CommonName = "Fiji",
                            NameAlpha3Code = "FJI"
                        },
                        new
                        {
                            Id = 74,
                            CommonName = "Finland",
                            NameAlpha3Code = "FIN"
                        },
                        new
                        {
                            Id = 75,
                            CommonName = "France",
                            NameAlpha3Code = "FRA"
                        },
                        new
                        {
                            Id = 76,
                            CommonName = "French Guiana",
                            NameAlpha3Code = "GUF"
                        },
                        new
                        {
                            Id = 77,
                            CommonName = "French Polynesia",
                            NameAlpha3Code = "PYF"
                        },
                        new
                        {
                            Id = 78,
                            CommonName = "French Southern and Antarctic Lands",
                            NameAlpha3Code = "ATF"
                        },
                        new
                        {
                            Id = 79,
                            CommonName = "Gabon",
                            NameAlpha3Code = "GAB"
                        },
                        new
                        {
                            Id = 80,
                            CommonName = "Gambia",
                            NameAlpha3Code = "GMB"
                        },
                        new
                        {
                            Id = 81,
                            CommonName = "Georgia",
                            NameAlpha3Code = "GEO"
                        },
                        new
                        {
                            Id = 82,
                            CommonName = "Germany",
                            NameAlpha3Code = "DEU"
                        },
                        new
                        {
                            Id = 83,
                            CommonName = "Ghana",
                            NameAlpha3Code = "GHA"
                        },
                        new
                        {
                            Id = 84,
                            CommonName = "Gibraltar",
                            NameAlpha3Code = "GIB"
                        },
                        new
                        {
                            Id = 85,
                            CommonName = "Greece",
                            NameAlpha3Code = "GRC"
                        },
                        new
                        {
                            Id = 86,
                            CommonName = "Greenland",
                            NameAlpha3Code = "GRL"
                        },
                        new
                        {
                            Id = 87,
                            CommonName = "Grenada",
                            NameAlpha3Code = "GRD"
                        },
                        new
                        {
                            Id = 88,
                            CommonName = "Guadeloupe",
                            NameAlpha3Code = "GLP"
                        },
                        new
                        {
                            Id = 89,
                            CommonName = "Guam",
                            NameAlpha3Code = "GUM"
                        },
                        new
                        {
                            Id = 90,
                            CommonName = "Guatemala",
                            NameAlpha3Code = "GTM"
                        },
                        new
                        {
                            Id = 91,
                            CommonName = "Guernsey",
                            NameAlpha3Code = "GGY"
                        },
                        new
                        {
                            Id = 92,
                            CommonName = "Guinea-Bissau",
                            NameAlpha3Code = "GNB"
                        },
                        new
                        {
                            Id = 93,
                            CommonName = "Guinea",
                            NameAlpha3Code = "GIN"
                        },
                        new
                        {
                            Id = 94,
                            CommonName = "Guyana",
                            NameAlpha3Code = "GUY"
                        },
                        new
                        {
                            Id = 95,
                            CommonName = "Haiti",
                            NameAlpha3Code = "HTI"
                        },
                        new
                        {
                            Id = 96,
                            CommonName = "Heard Island and McDonald Islands",
                            NameAlpha3Code = "HMD"
                        },
                        new
                        {
                            Id = 97,
                            CommonName = "Honduras",
                            NameAlpha3Code = "HND"
                        },
                        new
                        {
                            Id = 98,
                            CommonName = "Hong Kong",
                            NameAlpha3Code = "HKG"
                        },
                        new
                        {
                            Id = 99,
                            CommonName = "Hungary",
                            NameAlpha3Code = "HUN"
                        },
                        new
                        {
                            Id = 100,
                            CommonName = "Iceland",
                            NameAlpha3Code = "ISL"
                        },
                        new
                        {
                            Id = 101,
                            CommonName = "India",
                            NameAlpha3Code = "IND"
                        },
                        new
                        {
                            Id = 102,
                            CommonName = "Indonesia",
                            NameAlpha3Code = "IDN"
                        },
                        new
                        {
                            Id = 103,
                            CommonName = "Iran",
                            NameAlpha3Code = "IRN"
                        },
                        new
                        {
                            Id = 104,
                            CommonName = "Iraq",
                            NameAlpha3Code = "IRQ"
                        },
                        new
                        {
                            Id = 105,
                            CommonName = "Ireland",
                            NameAlpha3Code = "IRL"
                        },
                        new
                        {
                            Id = 106,
                            CommonName = "Isle of Man",
                            NameAlpha3Code = "IMN"
                        },
                        new
                        {
                            Id = 107,
                            CommonName = "Israel",
                            NameAlpha3Code = "ISR"
                        },
                        new
                        {
                            Id = 108,
                            CommonName = "Italy",
                            NameAlpha3Code = "ITA"
                        },
                        new
                        {
                            Id = 109,
                            CommonName = "Ivory Coast",
                            NameAlpha3Code = "CIV"
                        },
                        new
                        {
                            Id = 110,
                            CommonName = "Jamaica",
                            NameAlpha3Code = "JAM"
                        },
                        new
                        {
                            Id = 111,
                            CommonName = "Japan",
                            NameAlpha3Code = "JPN"
                        },
                        new
                        {
                            Id = 112,
                            CommonName = "Jersey",
                            NameAlpha3Code = "JEY"
                        },
                        new
                        {
                            Id = 113,
                            CommonName = "Jordan",
                            NameAlpha3Code = "JOR"
                        },
                        new
                        {
                            Id = 114,
                            CommonName = "Kazakhstan",
                            NameAlpha3Code = "KAZ"
                        },
                        new
                        {
                            Id = 115,
                            CommonName = "Kenya",
                            NameAlpha3Code = "KEN"
                        },
                        new
                        {
                            Id = 116,
                            CommonName = "Kiribati",
                            NameAlpha3Code = "KIR"
                        },
                        new
                        {
                            Id = 117,
                            CommonName = "Kuwait",
                            NameAlpha3Code = "KWT"
                        },
                        new
                        {
                            Id = 118,
                            CommonName = "Kyrgyzstan",
                            NameAlpha3Code = "KGZ"
                        },
                        new
                        {
                            Id = 119,
                            CommonName = "Laos",
                            NameAlpha3Code = "LAO"
                        },
                        new
                        {
                            Id = 120,
                            CommonName = "Latvia",
                            NameAlpha3Code = "LVA"
                        },
                        new
                        {
                            Id = 121,
                            CommonName = "Lebanon",
                            NameAlpha3Code = "LBN"
                        },
                        new
                        {
                            Id = 122,
                            CommonName = "Lesotho",
                            NameAlpha3Code = "LSO"
                        },
                        new
                        {
                            Id = 123,
                            CommonName = "Liberia",
                            NameAlpha3Code = "LBR"
                        },
                        new
                        {
                            Id = 124,
                            CommonName = "Libya",
                            NameAlpha3Code = "LBY"
                        },
                        new
                        {
                            Id = 125,
                            CommonName = "Liechtenstein",
                            NameAlpha3Code = "LIE"
                        },
                        new
                        {
                            Id = 126,
                            CommonName = "Lithuania",
                            NameAlpha3Code = "LTU"
                        },
                        new
                        {
                            Id = 127,
                            CommonName = "Luxembourg",
                            NameAlpha3Code = "LUX"
                        },
                        new
                        {
                            Id = 128,
                            CommonName = "Macau",
                            NameAlpha3Code = "MAC"
                        },
                        new
                        {
                            Id = 129,
                            CommonName = "Madagascar",
                            NameAlpha3Code = "MDG"
                        },
                        new
                        {
                            Id = 130,
                            CommonName = "Malawi",
                            NameAlpha3Code = "MWI"
                        },
                        new
                        {
                            Id = 131,
                            CommonName = "Malaysia",
                            NameAlpha3Code = "MYS"
                        },
                        new
                        {
                            Id = 132,
                            CommonName = "Maldives",
                            NameAlpha3Code = "MDV"
                        },
                        new
                        {
                            Id = 133,
                            CommonName = "Mali",
                            NameAlpha3Code = "MLI"
                        },
                        new
                        {
                            Id = 134,
                            CommonName = "Malta",
                            NameAlpha3Code = "MLT"
                        },
                        new
                        {
                            Id = 135,
                            CommonName = "Marshall Islands",
                            NameAlpha3Code = "MHL"
                        },
                        new
                        {
                            Id = 136,
                            CommonName = "Martinique",
                            NameAlpha3Code = "MTQ"
                        },
                        new
                        {
                            Id = 137,
                            CommonName = "Mauritania",
                            NameAlpha3Code = "MRT"
                        },
                        new
                        {
                            Id = 138,
                            CommonName = "Mauritius",
                            NameAlpha3Code = "MUS"
                        },
                        new
                        {
                            Id = 139,
                            CommonName = "Mayotte",
                            NameAlpha3Code = "MYT"
                        },
                        new
                        {
                            Id = 140,
                            CommonName = "Mexico",
                            NameAlpha3Code = "MEX"
                        },
                        new
                        {
                            Id = 141,
                            CommonName = "Micronesia",
                            NameAlpha3Code = "FSM"
                        },
                        new
                        {
                            Id = 142,
                            CommonName = "Moldova",
                            NameAlpha3Code = "MDA"
                        },
                        new
                        {
                            Id = 143,
                            CommonName = "Monaco",
                            NameAlpha3Code = "MCO"
                        },
                        new
                        {
                            Id = 144,
                            CommonName = "Mongolia",
                            NameAlpha3Code = "MNG"
                        },
                        new
                        {
                            Id = 145,
                            CommonName = "Montenegro",
                            NameAlpha3Code = "MNE"
                        },
                        new
                        {
                            Id = 146,
                            CommonName = "Montserrat",
                            NameAlpha3Code = "MSR"
                        },
                        new
                        {
                            Id = 147,
                            CommonName = "Morocco",
                            NameAlpha3Code = "MAR"
                        },
                        new
                        {
                            Id = 148,
                            CommonName = "Mozambique",
                            NameAlpha3Code = "MOZ"
                        },
                        new
                        {
                            Id = 149,
                            CommonName = "Myanmar",
                            NameAlpha3Code = "MMR"
                        },
                        new
                        {
                            Id = 150,
                            CommonName = "Namibia",
                            NameAlpha3Code = "NAM"
                        },
                        new
                        {
                            Id = 151,
                            CommonName = "Nauru",
                            NameAlpha3Code = "NRU"
                        },
                        new
                        {
                            Id = 152,
                            CommonName = "Nepal",
                            NameAlpha3Code = "NPL"
                        },
                        new
                        {
                            Id = 153,
                            CommonName = "Netherlands",
                            NameAlpha3Code = "NLD"
                        },
                        new
                        {
                            Id = 154,
                            CommonName = "New Caledonia",
                            NameAlpha3Code = "NCL"
                        },
                        new
                        {
                            Id = 155,
                            CommonName = "New Zealand",
                            NameAlpha3Code = "NZL"
                        },
                        new
                        {
                            Id = 156,
                            CommonName = "Nicaragua",
                            NameAlpha3Code = "NIC"
                        },
                        new
                        {
                            Id = 157,
                            CommonName = "Nigeria",
                            NameAlpha3Code = "NGA"
                        },
                        new
                        {
                            Id = 158,
                            CommonName = "Niger",
                            NameAlpha3Code = "NER"
                        },
                        new
                        {
                            Id = 159,
                            CommonName = "Niue",
                            NameAlpha3Code = "NIU"
                        },
                        new
                        {
                            Id = 160,
                            CommonName = "Norfolk Island",
                            NameAlpha3Code = "NFK"
                        },
                        new
                        {
                            Id = 161,
                            CommonName = "Northern Mariana Islands",
                            NameAlpha3Code = "MNP"
                        },
                        new
                        {
                            Id = 162,
                            CommonName = "North Korea",
                            NameAlpha3Code = "PRK"
                        },
                        new
                        {
                            Id = 163,
                            CommonName = "North Macedonia",
                            NameAlpha3Code = "MKD"
                        },
                        new
                        {
                            Id = 164,
                            CommonName = "Norway",
                            NameAlpha3Code = "NOR"
                        },
                        new
                        {
                            Id = 165,
                            CommonName = "Oman",
                            NameAlpha3Code = "OMN"
                        },
                        new
                        {
                            Id = 166,
                            CommonName = "Pakistan",
                            NameAlpha3Code = "PAK"
                        },
                        new
                        {
                            Id = 167,
                            CommonName = "Palau",
                            NameAlpha3Code = "PLW"
                        },
                        new
                        {
                            Id = 168,
                            CommonName = "Palestine",
                            NameAlpha3Code = "PSE"
                        },
                        new
                        {
                            Id = 169,
                            CommonName = "Panama",
                            NameAlpha3Code = "PAN"
                        },
                        new
                        {
                            Id = 170,
                            CommonName = "Papua New Guinea",
                            NameAlpha3Code = "PNG"
                        },
                        new
                        {
                            Id = 171,
                            CommonName = "Paraguay",
                            NameAlpha3Code = "PRY"
                        },
                        new
                        {
                            Id = 172,
                            CommonName = "Peru",
                            NameAlpha3Code = "PER"
                        },
                        new
                        {
                            Id = 173,
                            CommonName = "Philippines",
                            NameAlpha3Code = "PHL"
                        },
                        new
                        {
                            Id = 174,
                            CommonName = "Pitcairn Islands",
                            NameAlpha3Code = "PCN"
                        },
                        new
                        {
                            Id = 175,
                            CommonName = "Poland",
                            NameAlpha3Code = "POL"
                        },
                        new
                        {
                            Id = 176,
                            CommonName = "Portugal",
                            NameAlpha3Code = "PRT"
                        },
                        new
                        {
                            Id = 177,
                            CommonName = "Puerto Rico",
                            NameAlpha3Code = "PRI"
                        },
                        new
                        {
                            Id = 178,
                            CommonName = "Qatar",
                            NameAlpha3Code = "QAT"
                        },
                        new
                        {
                            Id = 179,
                            CommonName = "Republic of the Congo",
                            NameAlpha3Code = "COG"
                        },
                        new
                        {
                            Id = 180,
                            CommonName = "Réunion",
                            NameAlpha3Code = "REU"
                        },
                        new
                        {
                            Id = 181,
                            CommonName = "Romania",
                            NameAlpha3Code = "ROU"
                        },
                        new
                        {
                            Id = 182,
                            CommonName = "Russia",
                            NameAlpha3Code = "RUS"
                        },
                        new
                        {
                            Id = 183,
                            CommonName = "Rwanda",
                            NameAlpha3Code = "RWA"
                        },
                        new
                        {
                            Id = 184,
                            CommonName = "Saint Barthélemy",
                            NameAlpha3Code = "BLM"
                        },
                        new
                        {
                            Id = 185,
                            CommonName = "Saint Helena, Ascension and Tristan da Cunha",
                            NameAlpha3Code = "SHN"
                        },
                        new
                        {
                            Id = 186,
                            CommonName = "Saint Kitts and Nevis",
                            NameAlpha3Code = "KNA"
                        },
                        new
                        {
                            Id = 187,
                            CommonName = "Saint Lucia",
                            NameAlpha3Code = "LCA"
                        },
                        new
                        {
                            Id = 188,
                            CommonName = "Saint Martin",
                            NameAlpha3Code = "MAF"
                        },
                        new
                        {
                            Id = 189,
                            CommonName = "Saint Pierre and Miquelon",
                            NameAlpha3Code = "SPM"
                        },
                        new
                        {
                            Id = 190,
                            CommonName = "Saint Vincent and the Grenadines",
                            NameAlpha3Code = "VCT"
                        },
                        new
                        {
                            Id = 191,
                            CommonName = "Samoa",
                            NameAlpha3Code = "WSM"
                        },
                        new
                        {
                            Id = 192,
                            CommonName = "San Marino",
                            NameAlpha3Code = "SMR"
                        },
                        new
                        {
                            Id = 193,
                            CommonName = "São Tomé and Príncipe",
                            NameAlpha3Code = "STP"
                        },
                        new
                        {
                            Id = 194,
                            CommonName = "Saudi Arabia",
                            NameAlpha3Code = "SAU"
                        },
                        new
                        {
                            Id = 195,
                            CommonName = "Senegal",
                            NameAlpha3Code = "SEN"
                        },
                        new
                        {
                            Id = 196,
                            CommonName = "Serbia",
                            NameAlpha3Code = "SRB"
                        },
                        new
                        {
                            Id = 197,
                            CommonName = "Seychelles",
                            NameAlpha3Code = "SYC"
                        },
                        new
                        {
                            Id = 198,
                            CommonName = "Sierra Leone",
                            NameAlpha3Code = "SLE"
                        },
                        new
                        {
                            Id = 199,
                            CommonName = "Singapore",
                            NameAlpha3Code = "SGP"
                        },
                        new
                        {
                            Id = 200,
                            CommonName = "Sint Maarten",
                            NameAlpha3Code = "SXM"
                        },
                        new
                        {
                            Id = 201,
                            CommonName = "Slovakia",
                            NameAlpha3Code = "SVK"
                        },
                        new
                        {
                            Id = 202,
                            CommonName = "Slovenia",
                            NameAlpha3Code = "SVN"
                        },
                        new
                        {
                            Id = 203,
                            CommonName = "Solomon Islands",
                            NameAlpha3Code = "SLB"
                        },
                        new
                        {
                            Id = 204,
                            CommonName = "Somalia",
                            NameAlpha3Code = "SOM"
                        },
                        new
                        {
                            Id = 205,
                            CommonName = "South Africa",
                            NameAlpha3Code = "ZAF"
                        },
                        new
                        {
                            Id = 206,
                            CommonName = "South Georgia",
                            NameAlpha3Code = "SGS"
                        },
                        new
                        {
                            Id = 207,
                            CommonName = "South Korea",
                            NameAlpha3Code = "KOR"
                        },
                        new
                        {
                            Id = 208,
                            CommonName = "South Sudan",
                            NameAlpha3Code = "SSD"
                        },
                        new
                        {
                            Id = 209,
                            CommonName = "Spain",
                            NameAlpha3Code = "ESP"
                        },
                        new
                        {
                            Id = 210,
                            CommonName = "Sri Lanka",
                            NameAlpha3Code = "LKA"
                        },
                        new
                        {
                            Id = 211,
                            CommonName = "Sudan",
                            NameAlpha3Code = "SDN"
                        },
                        new
                        {
                            Id = 212,
                            CommonName = "Suriname",
                            NameAlpha3Code = "SUR"
                        },
                        new
                        {
                            Id = 213,
                            CommonName = "Svalbard and Jan Mayen",
                            NameAlpha3Code = "SJM"
                        },
                        new
                        {
                            Id = 214,
                            CommonName = "Eswatini",
                            NameAlpha3Code = "SWZ"
                        },
                        new
                        {
                            Id = 215,
                            CommonName = "Sweden",
                            NameAlpha3Code = "SWE"
                        },
                        new
                        {
                            Id = 216,
                            CommonName = "Switzerland",
                            NameAlpha3Code = "CHE"
                        },
                        new
                        {
                            Id = 217,
                            CommonName = "Syria",
                            NameAlpha3Code = "SYR"
                        },
                        new
                        {
                            Id = 218,
                            CommonName = "Taiwan",
                            NameAlpha3Code = "TWN"
                        },
                        new
                        {
                            Id = 219,
                            CommonName = "Tajikistan",
                            NameAlpha3Code = "TJK"
                        },
                        new
                        {
                            Id = 220,
                            CommonName = "Tanzania",
                            NameAlpha3Code = "TZA"
                        },
                        new
                        {
                            Id = 221,
                            CommonName = "Thailand",
                            NameAlpha3Code = "THA"
                        },
                        new
                        {
                            Id = 222,
                            CommonName = "Timor-Leste",
                            NameAlpha3Code = "TLS"
                        },
                        new
                        {
                            Id = 223,
                            CommonName = "Togo",
                            NameAlpha3Code = "TGO"
                        },
                        new
                        {
                            Id = 224,
                            CommonName = "Tokelau",
                            NameAlpha3Code = "TKL"
                        },
                        new
                        {
                            Id = 225,
                            CommonName = "Tonga",
                            NameAlpha3Code = "TON"
                        },
                        new
                        {
                            Id = 226,
                            CommonName = "Trinidad and Tobago",
                            NameAlpha3Code = "TTO"
                        },
                        new
                        {
                            Id = 227,
                            CommonName = "Tunisia",
                            NameAlpha3Code = "TUN"
                        },
                        new
                        {
                            Id = 228,
                            CommonName = "Turkey",
                            NameAlpha3Code = "TUR"
                        },
                        new
                        {
                            Id = 229,
                            CommonName = "Turkmenistan",
                            NameAlpha3Code = "TKM"
                        },
                        new
                        {
                            Id = 230,
                            CommonName = "Turks and Caicos Islands",
                            NameAlpha3Code = "TCA"
                        },
                        new
                        {
                            Id = 231,
                            CommonName = "Tuvalu",
                            NameAlpha3Code = "TUV"
                        },
                        new
                        {
                            Id = 232,
                            CommonName = "Uganda",
                            NameAlpha3Code = "UGA"
                        },
                        new
                        {
                            Id = 233,
                            CommonName = "Ukraine",
                            NameAlpha3Code = "UKR"
                        },
                        new
                        {
                            Id = 234,
                            CommonName = "United Arab Emirates",
                            NameAlpha3Code = "ARE"
                        },
                        new
                        {
                            Id = 235,
                            CommonName = "United Kingdom",
                            NameAlpha3Code = "GBR"
                        },
                        new
                        {
                            Id = 236,
                            CommonName = "United States",
                            NameAlpha3Code = "USA"
                        },
                        new
                        {
                            Id = 237,
                            CommonName = "United States Minor Outlying Islands",
                            NameAlpha3Code = "UMI"
                        },
                        new
                        {
                            Id = 238,
                            CommonName = "United States Virgin Islands",
                            NameAlpha3Code = "VIR"
                        },
                        new
                        {
                            Id = 239,
                            CommonName = "Uruguay",
                            NameAlpha3Code = "URY"
                        },
                        new
                        {
                            Id = 240,
                            CommonName = "Uzbekistan",
                            NameAlpha3Code = "UZB"
                        },
                        new
                        {
                            Id = 241,
                            CommonName = "Vanuatu",
                            NameAlpha3Code = "VUT"
                        },
                        new
                        {
                            Id = 242,
                            CommonName = "Vatican City",
                            NameAlpha3Code = "VAT"
                        },
                        new
                        {
                            Id = 243,
                            CommonName = "Venezuela",
                            NameAlpha3Code = "VEN"
                        },
                        new
                        {
                            Id = 244,
                            CommonName = "Vietnam",
                            NameAlpha3Code = "VNM"
                        },
                        new
                        {
                            Id = 245,
                            CommonName = "Wallis and Futuna",
                            NameAlpha3Code = "WLF"
                        },
                        new
                        {
                            Id = 246,
                            CommonName = "Western Sahara",
                            NameAlpha3Code = "ESH"
                        },
                        new
                        {
                            Id = 247,
                            CommonName = "Yemen",
                            NameAlpha3Code = "YEM"
                        },
                        new
                        {
                            Id = 248,
                            CommonName = "Zambia",
                            NameAlpha3Code = "ZMB"
                        },
                        new
                        {
                            Id = 249,
                            CommonName = "Zimbabwe",
                            NameAlpha3Code = "ZWE"
                        });
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Film-Noir"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Game-Show"
                        },
                        new
                        {
                            Id = 13,
                            Name = "History"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Musical"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 18,
                            Name = "News"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Reality-TV"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Short"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Talk-Show"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 26,
                            Name = "War"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.PhysicalMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("MovieId");

                    b.ToTable("PhysicalMovies");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhysicalMovieId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RentalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhysicalMovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Client"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Manager"
                        });
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CountryOfOriginMovie", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.CountryOfOrigin", null)
                        .WithMany()
                        .HasForeignKey("CountriesOfOriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.PhysicalMovie", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Domain.Entities.Movie", "Movie")
                        .WithMany("PhysicalMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Rental", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.PhysicalMovie", "PhysicalMovie")
                        .WithMany("Rentals")
                        .HasForeignKey("PhysicalMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Domain.Entities.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalMovie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Review", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.User", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Movie", b =>
                {
                    b.Navigation("PhysicalMovies");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.PhysicalMovie", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.User", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
