// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRental.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieRental.Infrastructure.Migrations
{
    [DbContext(typeof(MovieRentalDbContext))]
    [Migration("20231202122346_AddNameAlpha3CodeAsKey")]
    partial class AddNameAlpha3CodeAsKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CountryOfOriginMovie", b =>
                {
                    b.Property<string>("CountriesOfOriginNameAlpha3Code")
                        .HasColumnType("text");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.HasKey("CountriesOfOriginNameAlpha3Code", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CountryOfOriginMovie");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.CountryOfOrigin", b =>
                {
                    b.Property<string>("NameAlpha3Code")
                        .HasColumnType("text");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NameAlpha3Code");

                    b.ToTable("CountriesOfOrigin");

                    b.HasData(
                        new
                        {
                            NameAlpha3Code = "AFG",
                            CommonName = "Afghanistan"
                        },
                        new
                        {
                            NameAlpha3Code = "ALA",
                            CommonName = "Åland Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "ALB",
                            CommonName = "Albania"
                        },
                        new
                        {
                            NameAlpha3Code = "DZA",
                            CommonName = "Algeria"
                        },
                        new
                        {
                            NameAlpha3Code = "ASM",
                            CommonName = "American Samoa"
                        },
                        new
                        {
                            NameAlpha3Code = "AND",
                            CommonName = "Andorra"
                        },
                        new
                        {
                            NameAlpha3Code = "AGO",
                            CommonName = "Angola"
                        },
                        new
                        {
                            NameAlpha3Code = "AIA",
                            CommonName = "Anguilla"
                        },
                        new
                        {
                            NameAlpha3Code = "ATA",
                            CommonName = "Antarctica"
                        },
                        new
                        {
                            NameAlpha3Code = "ATG",
                            CommonName = "Antigua and Barbuda"
                        },
                        new
                        {
                            NameAlpha3Code = "ARG",
                            CommonName = "Argentina"
                        },
                        new
                        {
                            NameAlpha3Code = "ARM",
                            CommonName = "Armenia"
                        },
                        new
                        {
                            NameAlpha3Code = "ABW",
                            CommonName = "Aruba"
                        },
                        new
                        {
                            NameAlpha3Code = "AUS",
                            CommonName = "Australia"
                        },
                        new
                        {
                            NameAlpha3Code = "AUT",
                            CommonName = "Austria"
                        },
                        new
                        {
                            NameAlpha3Code = "AZE",
                            CommonName = "Azerbaijan"
                        },
                        new
                        {
                            NameAlpha3Code = "BHS",
                            CommonName = "Bahamas"
                        },
                        new
                        {
                            NameAlpha3Code = "BHR",
                            CommonName = "Bahrain"
                        },
                        new
                        {
                            NameAlpha3Code = "BGD",
                            CommonName = "Bangladesh"
                        },
                        new
                        {
                            NameAlpha3Code = "BRB",
                            CommonName = "Barbados"
                        },
                        new
                        {
                            NameAlpha3Code = "BLR",
                            CommonName = "Belarus"
                        },
                        new
                        {
                            NameAlpha3Code = "BEL",
                            CommonName = "Belgium"
                        },
                        new
                        {
                            NameAlpha3Code = "BLZ",
                            CommonName = "Belize"
                        },
                        new
                        {
                            NameAlpha3Code = "BEN",
                            CommonName = "Benin"
                        },
                        new
                        {
                            NameAlpha3Code = "BMU",
                            CommonName = "Bermuda"
                        },
                        new
                        {
                            NameAlpha3Code = "BTN",
                            CommonName = "Bhutan"
                        },
                        new
                        {
                            NameAlpha3Code = "BOL",
                            CommonName = "Bolivia"
                        },
                        new
                        {
                            NameAlpha3Code = "BIH",
                            CommonName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            NameAlpha3Code = "BWA",
                            CommonName = "Botswana"
                        },
                        new
                        {
                            NameAlpha3Code = "BVT",
                            CommonName = "Bouvet Island"
                        },
                        new
                        {
                            NameAlpha3Code = "BRA",
                            CommonName = "Brazil"
                        },
                        new
                        {
                            NameAlpha3Code = "IOT",
                            CommonName = "British Indian Ocean Territory"
                        },
                        new
                        {
                            NameAlpha3Code = "VGB",
                            CommonName = "British Virgin Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "BRN",
                            CommonName = "Brunei"
                        },
                        new
                        {
                            NameAlpha3Code = "BGR",
                            CommonName = "Bulgaria"
                        },
                        new
                        {
                            NameAlpha3Code = "BFA",
                            CommonName = "Burkina Faso"
                        },
                        new
                        {
                            NameAlpha3Code = "BDI",
                            CommonName = "Burundi"
                        },
                        new
                        {
                            NameAlpha3Code = "KHM",
                            CommonName = "Cambodia"
                        },
                        new
                        {
                            NameAlpha3Code = "CMR",
                            CommonName = "Cameroon"
                        },
                        new
                        {
                            NameAlpha3Code = "CAN",
                            CommonName = "Canada"
                        },
                        new
                        {
                            NameAlpha3Code = "CPV",
                            CommonName = "Cape Verde"
                        },
                        new
                        {
                            NameAlpha3Code = "BES",
                            CommonName = "Caribbean Netherlands"
                        },
                        new
                        {
                            NameAlpha3Code = "CYM",
                            CommonName = "Cayman Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "CAF",
                            CommonName = "Central African Republic"
                        },
                        new
                        {
                            NameAlpha3Code = "TCD",
                            CommonName = "Chad"
                        },
                        new
                        {
                            NameAlpha3Code = "CHL",
                            CommonName = "Chile"
                        },
                        new
                        {
                            NameAlpha3Code = "CHN",
                            CommonName = "China"
                        },
                        new
                        {
                            NameAlpha3Code = "CXR",
                            CommonName = "Christmas Island"
                        },
                        new
                        {
                            NameAlpha3Code = "CCK",
                            CommonName = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "COL",
                            CommonName = "Colombia"
                        },
                        new
                        {
                            NameAlpha3Code = "COM",
                            CommonName = "Comoros"
                        },
                        new
                        {
                            NameAlpha3Code = "COD",
                            CommonName = "DR Congo"
                        },
                        new
                        {
                            NameAlpha3Code = "COK",
                            CommonName = "Cook Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "CRI",
                            CommonName = "Costa Rica"
                        },
                        new
                        {
                            NameAlpha3Code = "HRV",
                            CommonName = "Croatia"
                        },
                        new
                        {
                            NameAlpha3Code = "CUB",
                            CommonName = "Cuba"
                        },
                        new
                        {
                            NameAlpha3Code = "CUW",
                            CommonName = "Curaçao"
                        },
                        new
                        {
                            NameAlpha3Code = "CYP",
                            CommonName = "Cyprus"
                        },
                        new
                        {
                            NameAlpha3Code = "CZE",
                            CommonName = "Czechia"
                        },
                        new
                        {
                            NameAlpha3Code = "DNK",
                            CommonName = "Denmark"
                        },
                        new
                        {
                            NameAlpha3Code = "DJI",
                            CommonName = "Djibouti"
                        },
                        new
                        {
                            NameAlpha3Code = "DMA",
                            CommonName = "Dominica"
                        },
                        new
                        {
                            NameAlpha3Code = "DOM",
                            CommonName = "Dominican Republic"
                        },
                        new
                        {
                            NameAlpha3Code = "ECU",
                            CommonName = "Ecuador"
                        },
                        new
                        {
                            NameAlpha3Code = "EGY",
                            CommonName = "Egypt"
                        },
                        new
                        {
                            NameAlpha3Code = "SLV",
                            CommonName = "El Salvador"
                        },
                        new
                        {
                            NameAlpha3Code = "GNQ",
                            CommonName = "Equatorial Guinea"
                        },
                        new
                        {
                            NameAlpha3Code = "ERI",
                            CommonName = "Eritrea"
                        },
                        new
                        {
                            NameAlpha3Code = "EST",
                            CommonName = "Estonia"
                        },
                        new
                        {
                            NameAlpha3Code = "ETH",
                            CommonName = "Ethiopia"
                        },
                        new
                        {
                            NameAlpha3Code = "FLK",
                            CommonName = "Falkland Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "FRO",
                            CommonName = "Faroe Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "FJI",
                            CommonName = "Fiji"
                        },
                        new
                        {
                            NameAlpha3Code = "FIN",
                            CommonName = "Finland"
                        },
                        new
                        {
                            NameAlpha3Code = "FRA",
                            CommonName = "France"
                        },
                        new
                        {
                            NameAlpha3Code = "GUF",
                            CommonName = "French Guiana"
                        },
                        new
                        {
                            NameAlpha3Code = "PYF",
                            CommonName = "French Polynesia"
                        },
                        new
                        {
                            NameAlpha3Code = "ATF",
                            CommonName = "French Southern and Antarctic Lands"
                        },
                        new
                        {
                            NameAlpha3Code = "GAB",
                            CommonName = "Gabon"
                        },
                        new
                        {
                            NameAlpha3Code = "GMB",
                            CommonName = "Gambia"
                        },
                        new
                        {
                            NameAlpha3Code = "GEO",
                            CommonName = "Georgia"
                        },
                        new
                        {
                            NameAlpha3Code = "DEU",
                            CommonName = "Germany"
                        },
                        new
                        {
                            NameAlpha3Code = "GHA",
                            CommonName = "Ghana"
                        },
                        new
                        {
                            NameAlpha3Code = "GIB",
                            CommonName = "Gibraltar"
                        },
                        new
                        {
                            NameAlpha3Code = "GRC",
                            CommonName = "Greece"
                        },
                        new
                        {
                            NameAlpha3Code = "GRL",
                            CommonName = "Greenland"
                        },
                        new
                        {
                            NameAlpha3Code = "GRD",
                            CommonName = "Grenada"
                        },
                        new
                        {
                            NameAlpha3Code = "GLP",
                            CommonName = "Guadeloupe"
                        },
                        new
                        {
                            NameAlpha3Code = "GUM",
                            CommonName = "Guam"
                        },
                        new
                        {
                            NameAlpha3Code = "GTM",
                            CommonName = "Guatemala"
                        },
                        new
                        {
                            NameAlpha3Code = "GGY",
                            CommonName = "Guernsey"
                        },
                        new
                        {
                            NameAlpha3Code = "GNB",
                            CommonName = "Guinea-Bissau"
                        },
                        new
                        {
                            NameAlpha3Code = "GIN",
                            CommonName = "Guinea"
                        },
                        new
                        {
                            NameAlpha3Code = "GUY",
                            CommonName = "Guyana"
                        },
                        new
                        {
                            NameAlpha3Code = "HTI",
                            CommonName = "Haiti"
                        },
                        new
                        {
                            NameAlpha3Code = "HMD",
                            CommonName = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "HND",
                            CommonName = "Honduras"
                        },
                        new
                        {
                            NameAlpha3Code = "HKG",
                            CommonName = "Hong Kong"
                        },
                        new
                        {
                            NameAlpha3Code = "HUN",
                            CommonName = "Hungary"
                        },
                        new
                        {
                            NameAlpha3Code = "ISL",
                            CommonName = "Iceland"
                        },
                        new
                        {
                            NameAlpha3Code = "IND",
                            CommonName = "India"
                        },
                        new
                        {
                            NameAlpha3Code = "IDN",
                            CommonName = "Indonesia"
                        },
                        new
                        {
                            NameAlpha3Code = "IRN",
                            CommonName = "Iran"
                        },
                        new
                        {
                            NameAlpha3Code = "IRQ",
                            CommonName = "Iraq"
                        },
                        new
                        {
                            NameAlpha3Code = "IRL",
                            CommonName = "Ireland"
                        },
                        new
                        {
                            NameAlpha3Code = "IMN",
                            CommonName = "Isle of Man"
                        },
                        new
                        {
                            NameAlpha3Code = "ISR",
                            CommonName = "Israel"
                        },
                        new
                        {
                            NameAlpha3Code = "ITA",
                            CommonName = "Italy"
                        },
                        new
                        {
                            NameAlpha3Code = "CIV",
                            CommonName = "Ivory Coast"
                        },
                        new
                        {
                            NameAlpha3Code = "JAM",
                            CommonName = "Jamaica"
                        },
                        new
                        {
                            NameAlpha3Code = "JPN",
                            CommonName = "Japan"
                        },
                        new
                        {
                            NameAlpha3Code = "JEY",
                            CommonName = "Jersey"
                        },
                        new
                        {
                            NameAlpha3Code = "JOR",
                            CommonName = "Jordan"
                        },
                        new
                        {
                            NameAlpha3Code = "KAZ",
                            CommonName = "Kazakhstan"
                        },
                        new
                        {
                            NameAlpha3Code = "KEN",
                            CommonName = "Kenya"
                        },
                        new
                        {
                            NameAlpha3Code = "KIR",
                            CommonName = "Kiribati"
                        },
                        new
                        {
                            NameAlpha3Code = "KWT",
                            CommonName = "Kuwait"
                        },
                        new
                        {
                            NameAlpha3Code = "KGZ",
                            CommonName = "Kyrgyzstan"
                        },
                        new
                        {
                            NameAlpha3Code = "LAO",
                            CommonName = "Laos"
                        },
                        new
                        {
                            NameAlpha3Code = "LVA",
                            CommonName = "Latvia"
                        },
                        new
                        {
                            NameAlpha3Code = "LBN",
                            CommonName = "Lebanon"
                        },
                        new
                        {
                            NameAlpha3Code = "LSO",
                            CommonName = "Lesotho"
                        },
                        new
                        {
                            NameAlpha3Code = "LBR",
                            CommonName = "Liberia"
                        },
                        new
                        {
                            NameAlpha3Code = "LBY",
                            CommonName = "Libya"
                        },
                        new
                        {
                            NameAlpha3Code = "LIE",
                            CommonName = "Liechtenstein"
                        },
                        new
                        {
                            NameAlpha3Code = "LTU",
                            CommonName = "Lithuania"
                        },
                        new
                        {
                            NameAlpha3Code = "LUX",
                            CommonName = "Luxembourg"
                        },
                        new
                        {
                            NameAlpha3Code = "MAC",
                            CommonName = "Macau"
                        },
                        new
                        {
                            NameAlpha3Code = "MDG",
                            CommonName = "Madagascar"
                        },
                        new
                        {
                            NameAlpha3Code = "MWI",
                            CommonName = "Malawi"
                        },
                        new
                        {
                            NameAlpha3Code = "MYS",
                            CommonName = "Malaysia"
                        },
                        new
                        {
                            NameAlpha3Code = "MDV",
                            CommonName = "Maldives"
                        },
                        new
                        {
                            NameAlpha3Code = "MLI",
                            CommonName = "Mali"
                        },
                        new
                        {
                            NameAlpha3Code = "MLT",
                            CommonName = "Malta"
                        },
                        new
                        {
                            NameAlpha3Code = "MHL",
                            CommonName = "Marshall Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "MTQ",
                            CommonName = "Martinique"
                        },
                        new
                        {
                            NameAlpha3Code = "MRT",
                            CommonName = "Mauritania"
                        },
                        new
                        {
                            NameAlpha3Code = "MUS",
                            CommonName = "Mauritius"
                        },
                        new
                        {
                            NameAlpha3Code = "MYT",
                            CommonName = "Mayotte"
                        },
                        new
                        {
                            NameAlpha3Code = "MEX",
                            CommonName = "Mexico"
                        },
                        new
                        {
                            NameAlpha3Code = "FSM",
                            CommonName = "Micronesia"
                        },
                        new
                        {
                            NameAlpha3Code = "MDA",
                            CommonName = "Moldova"
                        },
                        new
                        {
                            NameAlpha3Code = "MCO",
                            CommonName = "Monaco"
                        },
                        new
                        {
                            NameAlpha3Code = "MNG",
                            CommonName = "Mongolia"
                        },
                        new
                        {
                            NameAlpha3Code = "MNE",
                            CommonName = "Montenegro"
                        },
                        new
                        {
                            NameAlpha3Code = "MSR",
                            CommonName = "Montserrat"
                        },
                        new
                        {
                            NameAlpha3Code = "MAR",
                            CommonName = "Morocco"
                        },
                        new
                        {
                            NameAlpha3Code = "MOZ",
                            CommonName = "Mozambique"
                        },
                        new
                        {
                            NameAlpha3Code = "MMR",
                            CommonName = "Myanmar"
                        },
                        new
                        {
                            NameAlpha3Code = "NAM",
                            CommonName = "Namibia"
                        },
                        new
                        {
                            NameAlpha3Code = "NRU",
                            CommonName = "Nauru"
                        },
                        new
                        {
                            NameAlpha3Code = "NPL",
                            CommonName = "Nepal"
                        },
                        new
                        {
                            NameAlpha3Code = "NLD",
                            CommonName = "Netherlands"
                        },
                        new
                        {
                            NameAlpha3Code = "NCL",
                            CommonName = "New Caledonia"
                        },
                        new
                        {
                            NameAlpha3Code = "NZL",
                            CommonName = "New Zealand"
                        },
                        new
                        {
                            NameAlpha3Code = "NIC",
                            CommonName = "Nicaragua"
                        },
                        new
                        {
                            NameAlpha3Code = "NGA",
                            CommonName = "Nigeria"
                        },
                        new
                        {
                            NameAlpha3Code = "NER",
                            CommonName = "Niger"
                        },
                        new
                        {
                            NameAlpha3Code = "NIU",
                            CommonName = "Niue"
                        },
                        new
                        {
                            NameAlpha3Code = "NFK",
                            CommonName = "Norfolk Island"
                        },
                        new
                        {
                            NameAlpha3Code = "MNP",
                            CommonName = "Northern Mariana Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "PRK",
                            CommonName = "North Korea"
                        },
                        new
                        {
                            NameAlpha3Code = "MKD",
                            CommonName = "North Macedonia"
                        },
                        new
                        {
                            NameAlpha3Code = "NOR",
                            CommonName = "Norway"
                        },
                        new
                        {
                            NameAlpha3Code = "OMN",
                            CommonName = "Oman"
                        },
                        new
                        {
                            NameAlpha3Code = "PAK",
                            CommonName = "Pakistan"
                        },
                        new
                        {
                            NameAlpha3Code = "PLW",
                            CommonName = "Palau"
                        },
                        new
                        {
                            NameAlpha3Code = "PSE",
                            CommonName = "Palestine"
                        },
                        new
                        {
                            NameAlpha3Code = "PAN",
                            CommonName = "Panama"
                        },
                        new
                        {
                            NameAlpha3Code = "PNG",
                            CommonName = "Papua New Guinea"
                        },
                        new
                        {
                            NameAlpha3Code = "PRY",
                            CommonName = "Paraguay"
                        },
                        new
                        {
                            NameAlpha3Code = "PER",
                            CommonName = "Peru"
                        },
                        new
                        {
                            NameAlpha3Code = "PHL",
                            CommonName = "Philippines"
                        },
                        new
                        {
                            NameAlpha3Code = "PCN",
                            CommonName = "Pitcairn Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "POL",
                            CommonName = "Poland"
                        },
                        new
                        {
                            NameAlpha3Code = "PRT",
                            CommonName = "Portugal"
                        },
                        new
                        {
                            NameAlpha3Code = "PRI",
                            CommonName = "Puerto Rico"
                        },
                        new
                        {
                            NameAlpha3Code = "QAT",
                            CommonName = "Qatar"
                        },
                        new
                        {
                            NameAlpha3Code = "COG",
                            CommonName = "Republic of the Congo"
                        },
                        new
                        {
                            NameAlpha3Code = "REU",
                            CommonName = "Réunion"
                        },
                        new
                        {
                            NameAlpha3Code = "ROU",
                            CommonName = "Romania"
                        },
                        new
                        {
                            NameAlpha3Code = "RUS",
                            CommonName = "Russia"
                        },
                        new
                        {
                            NameAlpha3Code = "RWA",
                            CommonName = "Rwanda"
                        },
                        new
                        {
                            NameAlpha3Code = "BLM",
                            CommonName = "Saint Barthélemy"
                        },
                        new
                        {
                            NameAlpha3Code = "SHN",
                            CommonName = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            NameAlpha3Code = "KNA",
                            CommonName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            NameAlpha3Code = "LCA",
                            CommonName = "Saint Lucia"
                        },
                        new
                        {
                            NameAlpha3Code = "MAF",
                            CommonName = "Saint Martin"
                        },
                        new
                        {
                            NameAlpha3Code = "SPM",
                            CommonName = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            NameAlpha3Code = "VCT",
                            CommonName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            NameAlpha3Code = "WSM",
                            CommonName = "Samoa"
                        },
                        new
                        {
                            NameAlpha3Code = "SMR",
                            CommonName = "San Marino"
                        },
                        new
                        {
                            NameAlpha3Code = "STP",
                            CommonName = "São Tomé and Príncipe"
                        },
                        new
                        {
                            NameAlpha3Code = "SAU",
                            CommonName = "Saudi Arabia"
                        },
                        new
                        {
                            NameAlpha3Code = "SEN",
                            CommonName = "Senegal"
                        },
                        new
                        {
                            NameAlpha3Code = "SRB",
                            CommonName = "Serbia"
                        },
                        new
                        {
                            NameAlpha3Code = "SYC",
                            CommonName = "Seychelles"
                        },
                        new
                        {
                            NameAlpha3Code = "SLE",
                            CommonName = "Sierra Leone"
                        },
                        new
                        {
                            NameAlpha3Code = "SGP",
                            CommonName = "Singapore"
                        },
                        new
                        {
                            NameAlpha3Code = "SXM",
                            CommonName = "Sint Maarten"
                        },
                        new
                        {
                            NameAlpha3Code = "SVK",
                            CommonName = "Slovakia"
                        },
                        new
                        {
                            NameAlpha3Code = "SVN",
                            CommonName = "Slovenia"
                        },
                        new
                        {
                            NameAlpha3Code = "SLB",
                            CommonName = "Solomon Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "SOM",
                            CommonName = "Somalia"
                        },
                        new
                        {
                            NameAlpha3Code = "ZAF",
                            CommonName = "South Africa"
                        },
                        new
                        {
                            NameAlpha3Code = "SGS",
                            CommonName = "South Georgia"
                        },
                        new
                        {
                            NameAlpha3Code = "KOR",
                            CommonName = "South Korea"
                        },
                        new
                        {
                            NameAlpha3Code = "SSD",
                            CommonName = "South Sudan"
                        },
                        new
                        {
                            NameAlpha3Code = "ESP",
                            CommonName = "Spain"
                        },
                        new
                        {
                            NameAlpha3Code = "LKA",
                            CommonName = "Sri Lanka"
                        },
                        new
                        {
                            NameAlpha3Code = "SDN",
                            CommonName = "Sudan"
                        },
                        new
                        {
                            NameAlpha3Code = "SUR",
                            CommonName = "Suriname"
                        },
                        new
                        {
                            NameAlpha3Code = "SJM",
                            CommonName = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            NameAlpha3Code = "SWZ",
                            CommonName = "Eswatini"
                        },
                        new
                        {
                            NameAlpha3Code = "SWE",
                            CommonName = "Sweden"
                        },
                        new
                        {
                            NameAlpha3Code = "CHE",
                            CommonName = "Switzerland"
                        },
                        new
                        {
                            NameAlpha3Code = "SYR",
                            CommonName = "Syria"
                        },
                        new
                        {
                            NameAlpha3Code = "TWN",
                            CommonName = "Taiwan"
                        },
                        new
                        {
                            NameAlpha3Code = "TJK",
                            CommonName = "Tajikistan"
                        },
                        new
                        {
                            NameAlpha3Code = "TZA",
                            CommonName = "Tanzania"
                        },
                        new
                        {
                            NameAlpha3Code = "THA",
                            CommonName = "Thailand"
                        },
                        new
                        {
                            NameAlpha3Code = "TLS",
                            CommonName = "Timor-Leste"
                        },
                        new
                        {
                            NameAlpha3Code = "TGO",
                            CommonName = "Togo"
                        },
                        new
                        {
                            NameAlpha3Code = "TKL",
                            CommonName = "Tokelau"
                        },
                        new
                        {
                            NameAlpha3Code = "TON",
                            CommonName = "Tonga"
                        },
                        new
                        {
                            NameAlpha3Code = "TTO",
                            CommonName = "Trinidad and Tobago"
                        },
                        new
                        {
                            NameAlpha3Code = "TUN",
                            CommonName = "Tunisia"
                        },
                        new
                        {
                            NameAlpha3Code = "TUR",
                            CommonName = "Turkey"
                        },
                        new
                        {
                            NameAlpha3Code = "TKM",
                            CommonName = "Turkmenistan"
                        },
                        new
                        {
                            NameAlpha3Code = "TCA",
                            CommonName = "Turks and Caicos Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "TUV",
                            CommonName = "Tuvalu"
                        },
                        new
                        {
                            NameAlpha3Code = "UGA",
                            CommonName = "Uganda"
                        },
                        new
                        {
                            NameAlpha3Code = "UKR",
                            CommonName = "Ukraine"
                        },
                        new
                        {
                            NameAlpha3Code = "ARE",
                            CommonName = "United Arab Emirates"
                        },
                        new
                        {
                            NameAlpha3Code = "GBR",
                            CommonName = "United Kingdom"
                        },
                        new
                        {
                            NameAlpha3Code = "USA",
                            CommonName = "United States"
                        },
                        new
                        {
                            NameAlpha3Code = "UMI",
                            CommonName = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "VIR",
                            CommonName = "United States Virgin Islands"
                        },
                        new
                        {
                            NameAlpha3Code = "URY",
                            CommonName = "Uruguay"
                        },
                        new
                        {
                            NameAlpha3Code = "UZB",
                            CommonName = "Uzbekistan"
                        },
                        new
                        {
                            NameAlpha3Code = "VUT",
                            CommonName = "Vanuatu"
                        },
                        new
                        {
                            NameAlpha3Code = "VAT",
                            CommonName = "Vatican City"
                        },
                        new
                        {
                            NameAlpha3Code = "VEN",
                            CommonName = "Venezuela"
                        },
                        new
                        {
                            NameAlpha3Code = "VNM",
                            CommonName = "Vietnam"
                        },
                        new
                        {
                            NameAlpha3Code = "WLF",
                            CommonName = "Wallis and Futuna"
                        },
                        new
                        {
                            NameAlpha3Code = "ESH",
                            CommonName = "Western Sahara"
                        },
                        new
                        {
                            NameAlpha3Code = "YEM",
                            CommonName = "Yemen"
                        },
                        new
                        {
                            NameAlpha3Code = "ZMB",
                            CommonName = "Zambia"
                        },
                        new
                        {
                            NameAlpha3Code = "ZWE",
                            CommonName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Formats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "4K"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blu-ray"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DVD"
                        });
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Film-Noir"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Game-Show"
                        },
                        new
                        {
                            Id = 13,
                            Name = "History"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Musical"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 18,
                            Name = "News"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Reality-TV"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Short"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Talk-Show"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 26,
                            Name = "War"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.PhysicalMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("MovieId");

                    b.ToTable("PhysicalMovies");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhysicalMovieId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RentalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhysicalMovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Client"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Manager"
                        });
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CountryOfOriginMovie", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.CountryOfOrigin", null)
                        .WithMany()
                        .HasForeignKey("CountriesOfOriginNameAlpha3Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.PhysicalMovie", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.Format", "Format")
                        .WithMany("PhysicalMovies")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Domain.Entities.Movie", "Movie")
                        .WithMany("PhysicalMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Rental", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.PhysicalMovie", "PhysicalMovie")
                        .WithMany("Rentals")
                        .HasForeignKey("PhysicalMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Domain.Entities.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalMovie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Review", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.User", b =>
                {
                    b.HasOne("MovieRental.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Format", b =>
                {
                    b.Navigation("PhysicalMovies");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Movie", b =>
                {
                    b.Navigation("PhysicalMovies");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.PhysicalMovie", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MovieRental.Domain.Entities.User", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
